# Site
name: "The Code Monks"
title: "The Code Monks"
description: "Description coming soon"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: thecodemonksorg@gmail.com

# Authors
authors:
  sanjay:
    name: Sanjay
    display_name: Spikey Sanju
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: dvlprsanju@gmail.com
    web: https://github.com/spikeysanju
    twitter: https://twitter.com/sanjay_spikey
    description: "A passionate Android and Fullstack Designer"
  waseem:
    name: Waseem
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://n0nu11.tech
    twitter: https://twitter.com/iamwaseem99
    description: "iOS Developer with Cybersecurity Skills"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
